### ISSUE TITLE
suggestion for gh-pages support

### ISSUE THREAD

**Issue by fedex1** [boopathi/sw-cache-all#1]
Thanks for sw-cache-all.

I created a fork and gh-pages branch to make it easy to run the demo.

See branch https://github.com/civic-data/sw-cache-all/tree/gh-pages

and 

see demo https://civic-data.github.io/sw-cache-all/

I don't see a way to create a pull request for a new branch.  But if you wish you can see the instructions here https://help.github.com/articles/creating-project-pages-manually/

**Comment by boopathi** [comment]
Sure will add the new branch. You can send the PR then.

**Comment by boopathi** [comment]
For now, I'm pushing examples/1 directly to gh-pages, using,

`git subtree push --prefix examples/1/ origin gh-pages`

**Comment by fedex1** [comment]
I think what you did works fine.

I added a pull request to add a comment to the readme file with the new example link.

Thanks!
